version: '3.8'

services:
  backend:
    build:
      context: ./JavaProject
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_TCP=db:5432
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=06092006
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.PostgreSQLDialect
      - PORT=8080
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:16
    volumes:
      - ./db:/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=freelance_db
      - POSTGRES_PASSWORD=06092006
      - PGDATA=/var/lib/postgresql/data/pgdata1
    networks:
      - app-network

  frontend:
    build:
      context: ./javalabsfront
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      - backend_url=backend:8080
      - Host=localhost
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge